// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepoCihan.Data;

#nullable disable

namespace RepoCihan.Migrations
{
    [DbContext(typeof(RepoCihanDBContext))]
    partial class RepoCihanDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RepoCihan.Model.Personel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdıveİkinciAdı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyadı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personeller");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88f7f6be-fb45-486f-b5ad-4b559e0b44c0"),
                            AdıveİkinciAdı = "Cihan",
                            Eposta = "cihan@guler.com",
                            Soyadı = "Güler",
                            Telefon = "05352223344"
                        },
                        new
                        {
                            Id = new Guid("069581dc-f0ed-4d48-9c12-a4d26b912833"),
                            AdıveİkinciAdı = "Paşa",
                            Eposta = "cihan@gulmez.com",
                            Soyadı = "Gülmez",
                            Telefon = "05341118977"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
